---
baseURL: "https://www.red-lang.org/"
languageCode: "en-us"
metaDataFormat: yaml
pluralizeListTitles: false
enableRobotsTXT: true
defaultContentLanguage: "en"
enableMissingTranslationPlaceholders: true

permalinks:
  blog: /:section/:year/:month/:slug/

taxonomies:
  tags: tags

languages:
  en:
    title: "English"
    params:
      CopyrightHTML: "Copyright &#xA9; 2018 FullStack Technologies Ltd"
    menu:
      main:
        - Name: "Home"
          Weight: 1
          Identifier: "home"
          URL: "/"
        - Name: "About"
          Weight: 2
          Identifier: "about"
          URL: "/about/"
        - Name: "Documentation"
          Weight: 3
          Identifier: "docs"
          URL: "https://github.com/red/red"
        - Name: "Blog"
          Weight: 4
          Identifier: "blog"
          URL: "/blog/"
        - Name: "Roadmap"
          Weight: 5
          Identifier: "roadmap"
          URL: "/roadmap/"
        - Name: "Download"
          Weight: 6
          Identifier: "download"
          URL: "/download/"
      social:
        - Name: "Reddit"
          Weight: 1
          Identifier: "reddit"
          URL: "https://reddit.com"
          Icon: "fa-reddit"
        - Name: "Facebook"
          Weight: 2
          Identifier: "facebook"
          URL: "https://facebook.com"
          Icon: "fa-facebook"
        - Name: "Twitter"
          Weight: 3
          Identifier: "twitter"
          URL: "https://twitter.com"
          Icon: "fa-twitter"
        - Name: "Gitter"
          Weight: 4
          Identifier: "gitter"
          URL: "https://gitter.com"
          Icon: "fa-gitter"
        - Name: "GitHub"
          Weight: 5
          Identifier: "github"
          URL: "https://github.com"
          Icon: "fa-github"
        - Name: "Telegram"
          Weight: 6
          Identifier: "telegram"
          URL: "https://telegram.com"
          Icon: "fa-telegram"
  fr:
    title: "Français"
    params:
      CopyrightHTML: "Droits d'auteur &#xA9; 2018 FullStack Technologies Ltd"
    blackfriday:
      angledQuotes: true
    menu:
      main:
        - Name: "Accueil"
          Weight: 1
          Identifier: "home"
          URL: "/fr/"
        - Name: "À propos"
          Weight: 2
          Identifier: "about"
          URL: "/about/"
        - Name: "Documentation"
          Weight: 3
          Identifier: "docs"
          URL: "https://github.com/red/red"
        - Name: "Blog"
          Weight: 4
          Identifier: "blog"
          URL: "/blog/"
        - Name: "Feuille de route"
          Weight: 5
          Identifier: "roadmap"
          URL: "/roadmap/"
        - Name: "Télécharger"
          Weight: 6
          Identifier: "download"
          URL: "/download/"
---
